import { FormDoc } from '@app/docs/FormDoc'

const frameworks = [{ value: 'react', label: 'React' }, { value: 'solid', label: 'Solid' }, { value: 'svelte', label: 'Svelte' }]

export const ZFieldDoc = () => <FormDoc tag="z-field" description="The standard label, guidance, and error wrapper for one Zest form control. It supplies visible context and forwards its label to the slotted Zest control as its accessible name." examples={[
	{ title: 'Use z-field for ordinary form controls', description: 'A form control needs a stable name. z-field keeps that name visible and passes it to the control inside its shadow DOM.', code: `<z-field label="Email address" description="We only use this for account notifications."><z-input type="email" placeholder="you@example.com" /></z-field>`, children: <z-field label="Email address" description="We only use this for account notifications."><z-input type="email" placeholder="you@example.com" /></z-field> },
	{ title: 'Use the same pattern for choices and longer answers', description: 'The wrapper works with select, combobox, textarea, and other Zest form controls—not just text inputs.', code: `<z-column gap="4"><z-field label="Framework"><z-select placeholder="Choose one" options={frameworks} /></z-field><z-field label="Project brief" description="A sentence or two is enough."><z-textarea rows="3" placeholder="What are you making?" /></z-field></z-column>`, children: <z-column gap="4"><z-field label="Framework"><z-select placeholder="Choose one" options={frameworks} /></z-field><z-field label="Project brief" description="A sentence or two is enough."><z-textarea rows={3} placeholder="What are you making?" /></z-field></z-column> },
	{ title: 'Make required state and errors clear', description: 'Use the required marker to set expectation. Replace supporting guidance with the specific next action when validation fails.', code: `<z-field label="Project name" is-required error="Use at least 3 characters."><z-input value="Hi" is-invalid /></z-field>`, children: <z-field label="Project name" isRequired error="Use at least 3 characters."><z-input value="Hi" isInvalid /></z-field> },
	{ title: 'Hide a label only when context is already visible', description: 'Compact or repeated controls can omit visible text, but must still have an accessible name. is-label-hidden keeps the wrapper label available to assistive technology.', code: `<z-field label="Search projects" is-label-hidden><z-input type="search" placeholder="Search projects" /></z-field>`, children: <z-field label="Search projects" isLabelHidden><z-input type="search" placeholder="Search projects" /></z-field> },
	{ title: 'Use label directly for compact contextual controls', description: 'When surrounding UI already makes the purpose obvious, skip z-field and give the control its accessible label directly. A placeholder is never its label.', code: `<z-combobox label="Filter framework" placeholder="Filter" options={frameworks} />`, children: <z-combobox label="Filter framework" placeholder="Filter" options={frameworks} /> }
]} reference={[
	{ term: 'label', detail: 'Visible field name and the accessible name forwarded to the first slotted Zest control. Use it for every standalone field.' },
	{ term: 'description', detail: 'Optional concise guidance shown below the control. It explains format, consequence, or expectation; it is not a replacement for the label.' },
	{ term: 'error', detail: 'Optional actionable validation message. When present, it replaces description in the helper area.' },
	{ term: 'is-required', detail: 'Adds a visible required marker. Also set is-required on the control when browser validation is needed.' },
	{ term: 'is-label-hidden', detail: 'Visually hides the wrapper label while preserving the accessible name. Reserve it for controls with clear nearby context.' },
	{ term: 'Accessibility rule', detail: 'Every interactive form control needs an accessible name. Prefer z-field; for compact contextual controls, pass label directly. Do not rely on placeholder text.' }
]} />
