import { ComponentDoc } from '@app/docs/ComponentDoc'
import { DocExample } from '@app/docs/DocExample'

export const ZSwapDoc = () => (
	<ComponentDoc tag="z-swap" category="Actions" description="A small, checkable two-face control. Use it when the control’s visible content itself should transform between off and on states.">
		<DocExample title="Provide two explicit faces" description="Put the inactive face in off and the active face in on." code={`<z-swap label="Theme" effect="rotate"><span slot="off">Light</span><span slot="on">Dark</span></z-swap>`}><z-swap label="Theme" effect="rotate"><span slot="off">Light</span><span slot="on">Dark</span></z-swap></DocExample>
		<DocExample title="Choose a motion that communicates change" description="Fade is calm, rotate suggests a mode change, and flip is more expressive." code={`<z-row gap="4"><z-swap label="Fade"><span slot="off">Off</span><span slot="on">On</span></z-swap><z-swap label="Rotate" effect="rotate"><span slot="off">−</span><span slot="on">+</span></z-swap><z-swap label="Flip" effect="flip"><span slot="off">A</span><span slot="on">B</span></z-swap></z-row>`}><z-row gap="4"><z-swap label="Fade"><span slot="off">Off</span><span slot="on">On</span></z-swap><z-swap label="Rotate" effect="rotate"><span slot="off">−</span><span slot="on">+</span></z-swap><z-swap label="Flip" effect="flip"><span slot="off">A</span><span slot="on">B</span></z-swap></z-row></DocExample>
		<DocExample title="Observe the value" description="The reflected is-active state lets external application state stay in sync." code={`swap.addEventListener('change', (event) => save(event.detail.active)); swap.isActive = true`}><z-text color="muted">Use <code>label</code> whenever the faces alone do not fully describe the control.</z-text></DocExample>
		<section className="doc-reference"><z-heading size="xs" tag="h2">Props and event</z-heading><dl><dt>kind</dt><dd>stack (default) overlays faces; beside presents them side by side.</dd><dt>effect</dt><dd>fade, rotate, or flip.</dd><dt>has-ghost</dt><dd>Leaves a faint inactive silhouette in beside mode.</dd><dt>is-active / change</dt><dd>Reflected state and a <code>{'{ active }'}</code> event payload.</dd></dl></section>
	</ComponentDoc>
)
