export const MIN_PLAYBACK_HUMANIZATION_MS = 0
export const MAX_PLAYBACK_HUMANIZATION_MS = 50

export const DEFAULT_OUTPUT_MIN_VELOCITY = 70
export const DEFAULT_OUTPUT_MAX_VELOCITY = 90

export const TICKS_PER_BEAT = 96
export const MIN_PROGRESSION_ITEM_DURATION_TICKS = 12
export const DEFAULT_PATTERN_SIGNAL_DURATION_TICKS = 24
