export const MIN_PROGRESSION_PIXELS_PER_BEAT = 40
export const MAX_PROGRESSION_PIXELS_PER_BEAT = 160
export const PROGRESSION_ZOOM_INCREMENT = 12
export const MIN_PLAYBACK_HUMANIZATION_MS = 0
export const MAX_PLAYBACK_HUMANIZATION_MS = 50
export const DEFAULT_OUTPUT_MIN_VELOCITY = 80
export const DEFAULT_OUTPUT_MAX_VELOCITY = 95
